[package]
name = "reggie"
version = "0.1.0"
edition = "2021"
authors = ["dgussler"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version="1.0.164", features=["derive"] }
serde_json = "1.0.96"
